name: deploy-static-site-main

on:
  push:
    branches:
      - main
      - index

jobs:
  deploy-static-site-uat:
    uses: ./.github/workflows/deploy-static-site-to-s3.yaml
    with:
      aws_iam_role: arn:aws:iam::722264665990:role/uat-metamask-deeplink-signer-github-actions
      aws_region: us-east-1
      build_name: static-site-build
      s3_bucket: signer.link-test.metamask.consensys.io
      s3_prefix: /public/uat/
      environment: uat

#   deploy-static-site-prd:
#     uses: ./.github/workflows/deploy-static-s3-site.yml
#     needs: [ deploy-static-site-uat ]
#     with:
#       aws_iam_role: arn:aws:iam::722264665990:role/uat-metamask-deeplink-signer-github-actions
#       aws_region: us-east-1
#       s3_bucket: signer.link.metamask.consensys.io
#       s3_prefix: /public/prd/
#       environment: prd
